# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

controllers:
    resource: routing.controllers

api_login_check:
    path: /api/login_check
    defaults: { _controller: 'lexik_jwt_authentication.handler.authentication_success' }